import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, ResponsiveContainer, XAxis, YAxis, Tooltip } from 'recharts';
import { Building2, Users, WalletCards, ShieldCheck, Search, Moon, Bell, MapPin } from 'lucide-react';
import './styles/index.css';
import { chartData, leadStages, metrics, modules, plotStatuses } from './data/crm';

function Card({ title, value }: { title: string; value: string }) { return <div className="glass rounded-3xl p-5 shadow-glass transition hover:-translate-y-1"><p className="text-sm text-slate-500">{title}</p><b className="mt-2 block text-2xl text-slate-900">{value}</b></div>; }
function Section({ title, children }: React.PropsWithChildren<{ title: string }>) { return <section className="glass rounded-3xl p-6 shadow-glass"><h2 className="mb-5 text-xl font-bold">{title}</h2>{children}</section>; }
function PlotMap() { return <div className="grid grid-cols-4 gap-3 md:grid-cols-8">{Array.from({length:32},(_,i)=>{const status=Object.keys(plotStatuses)[i%4] as keyof typeof plotStatuses;return <div key={i} className={`rounded-2xl p-3 text-center text-xs font-bold text-white ${plotStatuses[status]}`}>A-{i+1}<br/><span className="font-medium">{status}</span></div>})}</div>; }
function App(){ const [portal,setPortal]=useState<'Admin'|'Associate'>('Admin'); return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#dbeafe,transparent_35%),#F8FAFC]">
  <header className="sticky top-0 z-10 border-b border-white/50 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div className="flex items-center gap-3"><div className="rounded-2xl bg-primary p-3 text-white"><Building2/></div><div><h1 className="text-xl font-black">AVYA HOME CRM</h1><p className="text-xs text-slate-500">Real Estate Plot Management Platform</p></div></div><nav className="hidden gap-2 md:flex"><button onClick={()=>setPortal('Admin')} className={`rounded-full px-4 py-2 ${portal==='Admin'?'bg-primary text-white':'bg-white'}`}>Admin Portal</button><button onClick={()=>setPortal('Associate')} className={`rounded-full px-4 py-2 ${portal==='Associate'?'bg-primary text-white':'bg-white'}`}>Associate Portal</button></nav><div className="flex gap-2"><Search/><Bell/><Moon/></div></div></header>
  <div className="mx-auto grid max-w-7xl gap-6 px-5 py-8 lg:grid-cols-[260px_1fr]"><aside className="glass rounded-3xl p-4 shadow-glass"><p className="mb-3 text-sm font-bold text-primary">{portal} Navigation</p>{modules.slice(0,portal==='Admin'?15:9).map(m=><div key={m} className="rounded-2xl px-3 py-2 text-sm hover:bg-blue-50">{m}</div>)}</aside><div className="space-y-6">
    <section className="rounded-[2rem] bg-gradient-to-r from-primary to-sky-400 p-8 text-white shadow-glass"><div className="max-w-2xl"><p className="font-semibold opacity-90"><ShieldCheck className="mr-2 inline"/>Secure JWT + RBAC + Audit Logs</p><h2 className="mt-3 text-4xl font-black">Premium enterprise CRM for projects, plots, bookings, payments, commissions and payouts.</h2><p className="mt-3 text-blue-50">Responsive PWA-ready interface with dark/light support, notification center, KYC document workflow, TDS, QR receipts and S3-compatible file storage.</p></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([t,v])=><Card key={t} title={t} value={v}/>)}</div>
    <div className="grid gap-6 xl:grid-cols-2"><Section title="Monthly Revenue Chart"><ResponsiveContainer height={260}><AreaChart data={chartData}><XAxis dataKey="month"/><YAxis/><Tooltip/><Area dataKey="revenue" stroke="#2563EB" fill="#93c5fd"/></AreaChart></ResponsiveContainer></Section><Section title="Associate Performance Chart"><ResponsiveContainer height={260}><BarChart data={chartData}><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="business" fill="#2563EB" radius={8}/></BarChart></ResponsiveContainer></Section><Section title="Team Growth Chart"><ResponsiveContainer height={240}><LineChart data={chartData}><XAxis dataKey="month"/><YAxis/><Tooltip/><Line dataKey="team" stroke="#0ea5e9" strokeWidth={3}/></LineChart></ResponsiveContainer></Section><Section title="Plot Sales Chart"><ResponsiveContainer height={240}><PieChart><Pie data={chartData} dataKey="plots" nameKey="month" outerRadius={85}>{chartData.map((_,i)=><Cell key={i} fill={['#22c55e','#facc15','#3b82f6','#ef4444','#38bdf8','#2563eb'][i]}/>)}</Pie></PieChart></ResponsiveContainer></Section></div>
    <Section title="Visual Plot Map"><div className="mb-4 flex flex-wrap gap-3 text-sm">{Object.entries(plotStatuses).map(([s,c])=><span key={s}><i className={`mr-2 inline-block h-3 w-3 rounded-full ${c}`}/>{s}</span>)}</div><PlotMap/></Section>
    <div className="grid gap-6 lg:grid-cols-2"><Section title="Lead Pipeline">{leadStages.map(s=><div className="mb-2 rounded-2xl bg-white p-3 shadow-sm" key={s}>{s}<span className="float-right text-primary">{Math.ceil(Math.random()*24)}</span></div>)}</Section><Section title="Referral Network"><div className="space-y-3"><div className="rounded-2xl bg-blue-600 p-4 text-white"><Users className="inline"/> You / Manager</div><div className="ml-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-blue-100 p-4">Direct Associate</div><div className="rounded-2xl bg-blue-100 p-4">Direct Associate</div><div className="rounded-2xl bg-sky-100 p-4">Sub Associate</div><div className="rounded-2xl bg-sky-100 p-4">Team Member</div></div></div></Section></div>
  </div></div><footer className="px-5 pb-8 text-center text-sm text-slate-500"><MapPin className="inline"/> Google Maps ready · <WalletCards className="inline"/> RTGS/NEFT/IMPS/Cash/Cheque/Online receipts</footer></main> }
createRoot(document.getElementById('root')!).render(<App/>);
